---
primaryHostname: example.com # CHANGE ME
Server:
  Users:
    - name: myuser # CHANGE ME
      # How to get encrypted password
      # Encrypt password for user - python3 -c 'import crypt; print(crypt.crypt("secret", "salt"))'
      passwordEncrypted: 'some encrypted password' # CHANGE ME
      superuser: 1
  RemoteSetup:
    ip: <installation server ip address>
    # sshPort: 22 # Will be disabled after hardness of server
    # sshPortHardness: 10233 # After hardness of server
    sshRootPass: '<installation server root password>' # Root password it can also be put as envoriment variable 'export SSHPASS' then comment this line out
  certbotEmail: '<admin@example.com>' # CHANGE ME
NginxSetup:
  install: 1 # 0 don't setup webserver, 1 => install nginx server and add websites # will deprece soon
  WebSites:
    - domainName: example.com # CHANGE ME  or COMMENT OUT LINES
      siteType: html
    # - domainName: test.example.com # CHANGE ME
    #   siteType: html
    # - domainName: example2.com # CHANGE ME
    #   siteType: html
  Paths:
    # wwwBase: /srv/www/
    # sitesAvailable: /etc/nginx/sites-available/
    # sitesEnabled: /etc/nginx/sites-enabled/