#/bin/bash

TCLI_LINUX_BASH_SERVERSETUP_PATH_INC="${TCLI_LINUX_BASH_SERVERSETUP_PATH_ROOT}/inc"
TCLI_LINUX_BASH_SERVERSETUP_PATH_LOG="${TCLI_LINUX_BASH_SERVERSETUP_PATH_ROOT}/log"
TCLI_LINUX_BASH_SERVERSETUP_PATH_CONF="${TCLI_LINUX_BASH_SERVERSETUP_PATH_ROOT}/conf"
TCLI_LINUX_BASH_SERVERSETUP_PATH_VENDOR="${TCLI_LINUX_BASH_SERVERSETUP_PATH_ROOT}/vendor"

TCLI_LINUX_BASH_SERVERSETUP_FILE_SETTINGS="${TCLI_LINUX_BASH_SERVERSETUP_PATH_CONF}/settings.json"

# Dependencies
TCLI_LINUX_BASH_DISTRIBUTION_DOWNLOAD="https://github.com/TirsvadCLI/Linux.Bash.Distribution/archive/refs/tags/v0.2.0.tar.gz"
TCLI_LINUX_BASH_LOGGER_DOWNLOAD="https://github.com/TirsvadCLI/Linux.Bash.Logger/archive/refs/tags/v0.3.1.tar.gz"
