#/bin/bash

TCLI_LINUX_BASH_SERVERSETUP_PATH_INC="${TCLI_LINUX_BASH_SERVERSETUP_PATH_ROOT}/inc"
TCLI_LINUX_BASH_SERVERSETUP_PATH_LOG="${TCLI_LINUX_BASH_SERVERSETUP_PATH_ROOT}/log"
TCLI_LINUX_BASH_SERVERSETUP_PATH_CONF="${TCLI_LINUX_BASH_SERVERSETUP_PATH_ROOT}/conf"
TCLI_LINUX_BASH_SERVERSETUP_PATH_VENDOR="${TCLI_LINUX_BASH_SERVERSETUP_PATH_ROOT}/vendor"

